[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none' ; default-src 'self' googleapis.com *.googleapis.com; script-src 'self' ; object-src  'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"